### ISSUE TITLE
How do you compare a thrown error to an ApolloError type?

### ISSUE THREAD

**Issue by danielmahon** [boltsource/apollo-errors#54]
If I set a shared list of known errors:
```js
import { createError, formatError } from 'apollo-errors';

export const PermissionsError = createError('PermissionsError', {
  message: 'Invalid permissions, you must be logged in to do this.',
});
export const UsernameTakenError = createError('UsernameTakenError', {
  message: 'Sorry, that username is taken.',
});
export const EmailRegisteredError = createError('EmailRegisteredError', {
  message: 'That email is already registered.',
});

export const errorTypes = {
  PermissionsError,
  UsernameTakenError,
  EmailRegisteredError,
};
```

How do you compare a thrown error to it's bound function? None of these seem to work

```js
new UsernameTakenError() instanceof errorTypes.UsernameTakenError; // true for any type, cant distinguish
new UsernameTakenError().isInstance; // true, cant distinguish
```

Simpliest way I found:

```js
throw new UsernameTakenError("This is SomeCaughtError");
...
...
new errorTypes.UsernameTakenError().name === SomeCaughtError.name;
```

I feel like I'm missing something simple 😕

**Comment by rosendi** [comment]
I'm also curious to know.

**Comment by thebigredgeek** [comment]
Hmm interesting, this sounds like a bug tbh.  You should be able to use the `instanceof` operator, as the error should be an instance of the class.  That said, I don't know if you can do that within the `formatError` block because GraphQL has already performed a bit of serialization and it's not the same class IIRC.  You should be able to type check with `instance` prior to the error being thrown past the resolver boundary.
